# This workflow will build a Java project with Gradle and upload the build artifacts

name: Build Project

on: [push, pull_request]

env:
  MINECRAFT_VERSION: 1.21
  VERSION: 1.21-snapshot

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Set version env
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --console=plain
      - name: Extract JAR from ZIP
        run: unzip build/libs/*.zip -d build/libs/extracted
      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: build-jar
          path: build/libs/extracted/*.jar
      - name: Upload original ZIP archive
        uses: actions/upload-artifact@v3
        with:
          name: build-zip
          path: build/libs/*.zip
